name: NuxKits
main: com.bukkit.N4th4.NuxKits.NuxKits
version: 1.5
depend:
    - PermissionsEx
commands:
    nuxkits:
        description: All of the NuxKits commands
        usage: Command unrecognised by NuxKits. Use /NuxKits help.